/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.dynamicdatamapping.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBFactoryUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.service.persistence.ClassNamePersistence;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.dynamicdatamapping.model.DDMStructureRestriction;
import com.liferay.portlet.dynamicdatamapping.service.DDMStructureRestrictionLocalService;
import com.liferay.portlet.dynamicdatamapping.service.persistence.DDMStructureRestrictionPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the d d m structure restriction local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureRestrictionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureRestrictionLocalServiceImpl
 * @see com.liferay.portlet.dynamicdatamapping.service.DDMStructureRestrictionLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class DDMStructureRestrictionLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements DDMStructureRestrictionLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.portlet.dynamicdatamapping.service.DDMStructureRestrictionLocalServiceUtil} to access the d d m structure restriction local service.
	 */

	/**
	 * Adds the d d m structure restriction to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ddmStructureRestriction the d d m structure restriction
	 * @return the d d m structure restriction that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DDMStructureRestriction addDDMStructureRestriction(
		DDMStructureRestriction ddmStructureRestriction) {
		ddmStructureRestriction.setNew(true);

		return ddmStructureRestrictionPersistence.update(ddmStructureRestriction);
	}

	/**
	 * Creates a new d d m structure restriction with the primary key. Does not add the d d m structure restriction to the database.
	 *
	 * @param structureRestrictionId the primary key for the new d d m structure restriction
	 * @return the new d d m structure restriction
	 */
	@Override
	public DDMStructureRestriction createDDMStructureRestriction(
		long structureRestrictionId) {
		return ddmStructureRestrictionPersistence.create(structureRestrictionId);
	}

	/**
	 * Deletes the d d m structure restriction with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param structureRestrictionId the primary key of the d d m structure restriction
	 * @return the d d m structure restriction that was removed
	 * @throws PortalException if a d d m structure restriction with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DDMStructureRestriction deleteDDMStructureRestriction(
		long structureRestrictionId) throws PortalException {
		return ddmStructureRestrictionPersistence.remove(structureRestrictionId);
	}

	/**
	 * Deletes the d d m structure restriction from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ddmStructureRestriction the d d m structure restriction
	 * @return the d d m structure restriction that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DDMStructureRestriction deleteDDMStructureRestriction(
		DDMStructureRestriction ddmStructureRestriction) {
		return ddmStructureRestrictionPersistence.remove(ddmStructureRestriction);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(DDMStructureRestriction.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return ddmStructureRestrictionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMStructureRestrictionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return ddmStructureRestrictionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMStructureRestrictionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return ddmStructureRestrictionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return ddmStructureRestrictionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return ddmStructureRestrictionPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public DDMStructureRestriction fetchDDMStructureRestriction(
		long structureRestrictionId) {
		return ddmStructureRestrictionPersistence.fetchByPrimaryKey(structureRestrictionId);
	}

	/**
	 * Returns the d d m structure restriction with the primary key.
	 *
	 * @param structureRestrictionId the primary key of the d d m structure restriction
	 * @return the d d m structure restriction
	 * @throws PortalException if a d d m structure restriction with the primary key could not be found
	 */
	@Override
	public DDMStructureRestriction getDDMStructureRestriction(
		long structureRestrictionId) throws PortalException {
		return ddmStructureRestrictionPersistence.findByPrimaryKey(structureRestrictionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(com.liferay.portlet.dynamicdatamapping.service.DDMStructureRestrictionLocalServiceUtil.getService());
		actionableDynamicQuery.setClass(DDMStructureRestriction.class);
		actionableDynamicQuery.setClassLoader(getClassLoader());

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"structureRestrictionId");

		return actionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(com.liferay.portlet.dynamicdatamapping.service.DDMStructureRestrictionLocalServiceUtil.getService());
		actionableDynamicQuery.setClass(DDMStructureRestriction.class);
		actionableDynamicQuery.setClassLoader(getClassLoader());

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"structureRestrictionId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return ddmStructureRestrictionLocalService.deleteDDMStructureRestriction((DDMStructureRestriction)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return ddmStructureRestrictionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the d d m structure restrictions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMStructureRestrictionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of d d m structure restrictions
	 * @param end the upper bound of the range of d d m structure restrictions (not inclusive)
	 * @return the range of d d m structure restrictions
	 */
	@Override
	public List<DDMStructureRestriction> getDDMStructureRestrictions(
		int start, int end) {
		return ddmStructureRestrictionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of d d m structure restrictions.
	 *
	 * @return the number of d d m structure restrictions
	 */
	@Override
	public int getDDMStructureRestrictionsCount() {
		return ddmStructureRestrictionPersistence.countAll();
	}

	/**
	 * Updates the d d m structure restriction in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ddmStructureRestriction the d d m structure restriction
	 * @return the d d m structure restriction that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DDMStructureRestriction updateDDMStructureRestriction(
		DDMStructureRestriction ddmStructureRestriction) {
		return ddmStructureRestrictionPersistence.update(ddmStructureRestriction);
	}

	/**
	 * Returns the d d m structure restriction local service.
	 *
	 * @return the d d m structure restriction local service
	 */
	public DDMStructureRestrictionLocalService getDDMStructureRestrictionLocalService() {
		return ddmStructureRestrictionLocalService;
	}

	/**
	 * Sets the d d m structure restriction local service.
	 *
	 * @param ddmStructureRestrictionLocalService the d d m structure restriction local service
	 */
	public void setDDMStructureRestrictionLocalService(
		DDMStructureRestrictionLocalService ddmStructureRestrictionLocalService) {
		this.ddmStructureRestrictionLocalService = ddmStructureRestrictionLocalService;
	}

	/**
	 * Returns the d d m structure restriction persistence.
	 *
	 * @return the d d m structure restriction persistence
	 */
	public DDMStructureRestrictionPersistence getDDMStructureRestrictionPersistence() {
		return ddmStructureRestrictionPersistence;
	}

	/**
	 * Sets the d d m structure restriction persistence.
	 *
	 * @param ddmStructureRestrictionPersistence the d d m structure restriction persistence
	 */
	public void setDDMStructureRestrictionPersistence(
		DDMStructureRestrictionPersistence ddmStructureRestrictionPersistence) {
		this.ddmStructureRestrictionPersistence = ddmStructureRestrictionPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.portlet.dynamicdatamapping.model.DDMStructureRestriction",
			ddmStructureRestrictionLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portlet.dynamicdatamapping.model.DDMStructureRestriction");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return DDMStructureRestriction.class;
	}

	protected String getModelClassName() {
		return DDMStructureRestriction.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = ddmStructureRestrictionPersistence.getDataSource();

			DB db = DBFactoryUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = DDMStructureRestrictionLocalService.class)
	protected DDMStructureRestrictionLocalService ddmStructureRestrictionLocalService;
	@BeanReference(type = DDMStructureRestrictionPersistence.class)
	protected DDMStructureRestrictionPersistence ddmStructureRestrictionPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ClassNameLocalService.class)
	protected com.liferay.portal.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.service.ClassNameService.class)
	protected com.liferay.portal.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
	private String _beanIdentifier;
}